import todo from "../images/TodoApp/aaa.png";
import hotels from "../images/Hotels/App-heores (19).png";
import appMine from "../images/NotesMine/Captura.JPG";
import appCars from "../images/CarsDemo/Captura.JPG";
import appGifos from "../images/AppGifs/a.png";
import calendarApp from "../images/Calendar/App-heores (55).png";
import appHeroes from "../images/AppHeroes/App-heores (57).png";
import devsUnited from "../images/DevsUnited/App-heores (7).png";

export const dataApps = [
  {
    id: 1,
    status: "Completo",
    testing: "En proceso",
    title: "Mini - Twitter",
    tools: ["React", "Firebase", "Git", "Github"],
    desc: "Esta app es una replica de como funciona Twitter, puedes escribir un tweet, borrar tu tweet, ver las publicaciones de otros usuarios y puedes darle me gusta y guardarlos como favorito. En tu perfil puedes ver los tweets que has escrito y puedes encontrar los tweets a los cuales les has dado me gusta facilmente. ",
    img: devsUnited,
    web: "https://fir-devs-united.web.app/register",
    github: "https://github.com/Martin10123/Devs_united",
    hosting: "Firebase hosting",
  },
  {
    id: 2,
    status: "Completo",
    testing: "En proceso",
    title: "App To Gifos",
    tools: ["React", "Firebase", "Git", "Github", "Api - Giphy-developer"],
    desc: "Esta fue una de las primeras aplicaciones que hice, Fue un reto para mi, ya que tenia que consumir una Api. Esta app te ayuda a buscar gifos de manera rapida y sencilla, puedes darle click a la imagen y esta te lleva directamente a la pagina original del gif.",
    img: appGifos,
    web: "https://martin10123.github.io/gifs/",
    github: "https://github.com/Martin10123/gifs",
    hosting: "Github pages",
  },
  {
    id: 3,
    status: "Completo",
    testing: "En proceso",
    title: "App to Note",
    tools: ["React", "Redux", "Firebase", "Git", "Github", "Cloudinary"],
    desc: "Esta app trata de escribir notas, pensamientos o inclusive citas que quieras recordar luego. En esta app puedes borrar, subir una foto y modificar la nota escrita.",
    img: appMine,
    web: "https://sql-demos10.web.app/auth",
    github: "https://github.com/Martin10123/Notes-App",
    hosting: "Firebase hosting",
  },
  {
    id: 4,
    status: "Completo",
    testing: "En proceso",
    title: "Calendar App",
    tools: [
      "React",
      "Redux",
      "Express",
      "MongoDB",
      "Heroku",
      "Git",
      "Github",
      "Otras dependencias",
    ],
    desc: "Esta app trata de un calendario, en el cual puedes escribir un evento, modificar ese evento y borrar ese evento. Es una app muy util ya que te ayuda a ordenar tus eventos agregandoles una fecha de inicio y fin.",
    img: calendarApp,
    web: "https://calendar-backend-martin.herokuapp.com",
    github: "https://github.com/Martin10123/Calendar_App",
    hosting: "Heroku",
  },
  {
    id: 5,
    status: "En proceso",
    testing: "En proceso",
    title: "Cars - Demo",
    tools: ["React", "Redux", "Firebase", "Git", "Github"],
    desc: "Esta es una demo de una agencia de carros, aún esta en proceso de construccion porque tiene muchas funcionalidades más las cuales hay que agregarle, en esta app podras promocionar autos, venderlos y comprar autos. Puedes mirar sus caracteristicas, al dueño del auto y sus datos, puedes comunicarte con el vendedor directamente para consultar detalles. Puedes ver los autos mas vendidos, los mas caros, los mas baratos, su año, su precio entre otras opciones.",
    img: appCars,
    web: "",
    github: "https://github.com/Martin10123/Auto-cars",
    hosting: "",
  },
  {
    id: 6,
    status: "En proceso",
    testing: "En proceso",
    title: "Todo App",
    tools: ["React", "Redux", "Firebase", "Git", "Github"],
    desc: "Esta es una App que contiene dos opciones, te da la opcion de escribir una nota o una tarea. Esta la cree cuando apenas empezaba a aprender redux, para afinar conceptos. Puedes revisar tu perfil y ahi podras ver las notas y tareas que guardaste, te dara la opción de ponerlas privada. Puedes ver tu perfil y hasta modificarlo.",
    img: todo,
    web: "",
    github: "https://github.com/Martin10123/Todo_App",
    hosting: "",
  },
  {
    id: 7,
    status: "Completo",
    testing: "Completo",
    title: "Heroes App",
    tools: ["React", "Firebase", "Git", "Github"],
    desc: "Esta es una app donde puedes ver a tu heroe favorito y mirar sus caracteristicas.",
    img: appHeroes,
    web: "",
    github: "https://github.com/Martin10123/App-heroes",
    hosting: "",
  },
  {
    id: 8,
    status: "Completo",
    testing: "En proceso",
    title: "Hotels",
    tools: ["React", "Git", "Github"],
    desc: "Esta fue mi primera aplicación creada con React, me costo un montón la verdad, todo era nuevo para mi, pero con ayuda pude hacerlo y desde ahi empece a comprender varios conceptos. Esta app te da la opción de buscar hoteles de diferentes paises, ya sea por su precio, tamaño y pais.",
    img: hotels,
    web: "https://martin10123.github.io/app-hotels/",
    github: "https://github.com/Martin10123/Proyect-Hoteles",
    hosting: "Github pages",
  },
];
